// Generated by CoffeeScript 1.7.1

/**
  @param {string} cmd
  @param {Array.<string>} args
 */

(function() {
  module.exports = function(cmd, args) {
    var bg;
    bg = require('gulp-bg');
    return bg(cmd, args);
  };

}).call(this);
