// Generated by CoffeeScript 1.7.1
(function() {
  var gulp;

  gulp = require('gulp');


  /**
    @param {(string|Array.<string>)} paths
    @param {Object} yargs
    @param {Function} done
   */

  module.exports = function(paths, yargs, done) {
    var args, bump, git, path, type;
    bump = require('gulp-bump');
    git = require('gulp-git');
    path = require('path');
    args = yargs.alias('m', 'minor').argv;
    type = args.major && 'major' || args.minor && 'minor' || 'patch';
    gulp.src(paths).pipe(bump({
      type: type
    })).pipe(gulp.dest('./')).on('end', (function(_this) {
      return function() {
        var message, version;
        version = require(path.join(_this.dirname, 'package')).version;
        message = "Bump " + version;
        return gulp.src(paths).pipe(git.add()).pipe(git.commit(message)).on('end', function() {
          return git.push('origin', 'master', {}, function() {
            return git.tag(version, message, {}, function() {
              return git.push('origin', 'master', {
                args: ' --tags'
              }, done);
            });
          });
        });
      };
    })(this));
  };

}).call(this);
