// Generated by CoffeeScript 1.7.1
(function() {
  var gulp;

  gulp = require('gulp');


  /**
    @return {Stream} Node.js Stream.
   */

  module.exports = function() {
    var concat;
    concat = require('gulp-concat');
    return gulp.src('tmp/deps?.js').pipe(concat('deps.js')).pipe(gulp.dest('tmp'));
  };

}).call(this);
