// Generated by CoffeeScript 1.7.1
(function() {
  var gulp;

  gulp = require('gulp');


  /**
    Remove transpiled files without their original source.
    @param {Object.<string, Array.<string>>} object Key is glob and value
      is list of extensions, for example: 'somefile.js': ['coffee', 'jsx']
   */

  module.exports = function(object) {
    var exts, filter, fs, glob, isOrphan, path, paths, rimraf, targets;
    filter = require('gulp-filter');
    fs = require('fs');
    path = require('path');
    rimraf = require('gulp-rimraf');
    paths = Object.keys(object);
    targets = {};
    for (glob in object) {
      exts = object[glob];
      targets[glob.match(/\.[^\.]+/)] = exts;
    }
    isOrphan = function(file) {
      var ext, target, _i, _len, _ref;
      ext = path.extname(file.path);
      _ref = targets[ext];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        target = _ref[_i];
        if (fs.existsSync(file.path.replace(ext, '.' + target))) {
          return false;
        }
      }
      return true;
    };
    return gulp.src(paths, {
      read: false
    }).pipe(filter(isOrphan)).pipe(rimraf());
  };

}).call(this);
