// Generated by CoffeeScript 1.7.1
(function() {
  var gulp;

  gulp = require('gulp');


  /**
    @param {(string|Array.<string>)} paths
    @return {Stream} Node.js Stream.
   */

  module.exports = function(paths) {
    var closureDeps;
    closureDeps = require('gulp-closure-deps');
    if (!Array.isArray(paths)) {
      paths = [paths];
    }
    return gulp.src(paths).pipe(closureDeps({
      fileName: 'deps0.js',
      prefix: this.depsPrefix
    })).pipe(gulp.dest('tmp'));
  };

}).call(this);
