// Generated by CoffeeScript 1.7.1

/**
  @param {string} dir
  @return {Array.<string>}
 */

(function() {
  module.exports = function(dir) {
    throw "Method getExterns is deprecated. Use getNodeJsExterns() instead. Update your gulpfile 'compile-serverapp', check github.com/steida/este.";
  };

}).call(this);
