// Generated by CoffeeScript 1.7.1

/**
  @return {Array.<string>}
 */

(function() {
  module.exports = function() {
    var nodeJsExterns;
    nodeJsExterns = require('nodejs-externs');
    return nodeJsExterns.getExternsAsListOfResolvedPaths();
  };

}).call(this);
