// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function() {
    if (!this.changedFilePath || !this.liveReload) {
      return;
    }
    return this.liveReload.changed(this.changedFilePath);
  };

}).call(this);
