// Generated by CoffeeScript 1.7.1

/**
  @param {string} target The file/uri to open.
  @param {string=} appName The application to be used to open the file. For
    example: 'chrome', 'firefox'.
  @return {ChildProcess} The child process object.
 */

(function() {
  module.exports = function(target, appName) {
    var open;
    if (appName == null) {
      appName = '';
    }
    open = require('open');
    return open(target, appName);
  };

}).call(this);
