// Generated by CoffeeScript 1.7.1

/**
  @return {boolean}
 */

(function() {
  module.exports = function() {
    var closureDeps;
    closureDeps = require('gulp-closure-deps');
    return closureDeps.changed(this.changedFilePath);
  };

}).call(this);
